'use client'
import { motion } from 'framer-motion'
import { useState } from 'react'
import StateCard from '../components/StateCard'
import StateModal from '../components/StateModal'
import InteractiveMap from '../components/InteractiveMap'

export default function States() {
  const [selectedState, setSelectedState] = useState<any>(null)
  const [isModalOpen, setIsModalOpen] = useState(false)
  const states = [
    // North India
    { name: 'Rajasthan', capital: 'Jaipur', famousFood: 'Dal Baati Churma', biggestFestival: 'Pushkar Fair', history: 'The Land of Maharajas, Rajasthan has been a center of Rajput warriors and royal dynasties for centuries. Known for magnificent palaces like Hawa Mahal and City Palace in Jaipur, and ancient forts like Mehrangarh Fort in Jodhpur. The desert landscape of Thar has shaped a unique culture of hospitality and valor.', detailedHistory: 'Rajasthan was historically divided into various princely states ruled by Rajput clans. The Sisodia and Kachhwaha dynasties were prominent. In the 18th-19th centuries, these states came under British rule. Post-independence, these princely states merged to form the state of Rajasthan. Rich in mineral resources and famous for traditional textile arts, jewelry, and miniature paintings.', speciality: 'Palaces, Forts, Desert Safari', image: '/images/states/rajasthan.jpeg', cardImage: '/images/states/rajasthan.jpeg', color: '#FF6B35', region: 'North' },
    { name: 'Punjab', capital: 'Chandigarh', famousFood: 'Makki di Roti & Sarson da Saag', biggestFestival: 'Baisakhi', history: 'Punjab, the land of five rivers, is known for its agricultural prosperity and Sikh heritage. The Golden Temple in Amritsar is one of the most sacred pilgrimage sites in the world. Punjab has been a cultural crossroads of North India with strong musical and dance traditions like Bhangra and Giddha.', detailedHistory: 'Historically, Punjab was ruled by various empires including Maurya, Mughal, and finally British. The Punjab region was divided between India and Pakistan in 1947. Post-partition, it became a major agricultural hub with the Green Revolution transforming its economy. The Sikh community plays a vital cultural role with contributions to arts, music, and agriculture.', speciality: 'Golden Temple, Agriculture, Bhangra', image: '/images/states/punjab.jpeg', cardImage: '/images/states/punjab.jpeg', color: '#FFD700', region: 'North' },
    { name: 'Haryana', capital: 'Chandigarh', famousFood: 'Bajra Khichdi', biggestFestival: 'Teej', history: 'Haryana is deeply rooted in ancient Indian history as the site of the Kurukshetra battlefield described in the Mahabharata. This state is known for its agricultural contribution and growing industrial development. The region has been home to numerous kingdoms and empires throughout history.', detailedHistory: 'Haryana was part of the Mauryan, Gupta, and later Mughal empires. After independence, it was formed from parts of Punjab and the erstwhile Himachal Pradesh in 1966. The state has developed into a major industrial and agricultural center. Traditional wrestling (Kushti) and martial arts have deep roots here.', speciality: 'Kurukshetra, Wrestling, Agriculture', image: '/images/states/haryana.jpeg', cardImage: '/images/states/haryana.jpeg', color: '#FF8C00', region: 'North' },
    { name: 'Uttar Pradesh', capital: 'Lucknow', famousFood: 'Lucknowi Biryani', biggestFestival: 'Kumbh Mela', history: 'Home to iconic monuments like the Taj Mahal, Varanasi temples, and Agra Fort, Uttar Pradesh is a treasure trove of Mughal and Rajput heritage. The Ganges River flows through this state, making it a spiritual center. Lucknow is famous for its refined culture, Nawabi architecture, and culinary traditions.', detailedHistory: 'Uttar Pradesh has been the seat of numerous empires including Maurya, Gupta, and Mughal. It was the center of the Indian independence movement with contributions from leaders like Pandit Jawaharlal Nehru. The state is home to universities, temples, and monuments of national importance. The Kumbh Mela held at Prayagraj attracts millions of pilgrims.', speciality: 'Taj Mahal, Varanasi, Mughal Heritage', image: '/images/states/up.jpeg', cardImage: '/images/states/up.jpeg', color: '#8B0000', region: 'North' },
    { name: 'Himachal Pradesh', capital: 'Shimla', famousFood: 'Dham', biggestFestival: 'Kullu Dussehra', history: 'Known as the Land of Gods, Himachal Pradesh is famous for its scenic beauty, apple orchards, and adventure tourism. Shimla was the summer capital during British rule. The region has a rich tradition of temple architecture and handicrafts. The Himalayas provide a stunning backdrop to this mountain state.', detailedHistory: 'Historically, Himachal Pradesh consisted of several princely states and hill kingdoms. These were brought under British control gradually and later merged with India. The state is known for its traditional arts like Pahari paintings, wood carving, and textile weaving. Hill stations like Shimla, Manali, and Dalhousie attract tourists from around the world.', speciality: 'Mountains, Apple Orchards, Adventure Sports', image: '/images/states/himachalpradesh.jpeg', cardImage: '/images/states/himachalpradesh.jpeg', color: '#87CEEB', region: 'North' },
    { name: 'Uttarakhand', capital: 'Dehradun', famousFood: 'Aloo ke Gutke', biggestFestival: 'Kumbh Mela', history: 'Uttarakhand, the Land of Gods, is home to the Char Dham pilgrimage sites (Kedarnath, Badrinath, Gangotri, Yamunotri). The state is a spiritual and adventure hub with trekking destinations and yoga centers. The Himalayan biodiversity hotspot is known for its natural beauty and cultural significance.', detailedHistory: 'Ancient Uttarakhand was ruled by various dynasties including the Katyuri dynasty. It was under British control as part of the United Provinces. Uttarakhand was formed as a separate state in 2000. The region is central to Hindu philosophy and spirituality with numerous ashrams and yoga centers. Traditional art forms like Kumaoni folk dance are integral to the culture.', speciality: 'Char Dham, Yoga, Himalayan Beauty', image: '/images/states/uttarakhand.jpeg', cardImage: '/images/states/uttarakhand.jpeg', color: '#4682B4', region: 'North' },
    { name: 'Jammu & Kashmir', capital: 'Srinagar', famousFood: 'Rogan Josh', biggestFestival: 'Shivratri', history: 'Often described as Paradise on Earth, Jammu & Kashmir is famous for its stunning landscapes, Dal Lake, and alpine meadows. The region has a rich Islamic and Hindu heritage with magnificent mosques and temples. Traditional crafts like Kashmir carpet weaving and papier-mâché are world-renowned. The Mughal gardens are architectural marvels.', detailedHistory: 'Kashmir was ruled by Hindu kings, Buddhist rulers, and later Muslim dynasties. The Mughal emperors were fascinated by Kashmir and built magnificent gardens. The region experienced colonial rule and later became a point of geopolitical significance. Modern Kashmir is known for its resilience, hospitality, and cultural richness. Traditional arts, music, and handicrafts are integral to Kashmiri identity.', speciality: 'Dal Lake, Mughal Gardens, Handicrafts', image: '/images/states/jammukashmir.jpeg', cardImage: '/images/states/jammukashmir.jpeg', color: '#9370DB', region: 'North' },
    
    // South India
    { name: 'Kerala', capital: 'Thiruvananthapuram', famousFood: 'Appam & Stew', biggestFestival: 'Onam', history: 'Known as God\'s Own Country, Kerala is famous for its backwaters, houseboats, and spice plantations. The state has been a hub of spice trade since ancient times, attracting traders from around the world. Kerala\'s literacy rate and quality of life are among the highest in India. The blend of Hindu, Christian, and Islamic cultures is unique to Kerala.', detailedHistory: 'Kerala was an ancient seat of Chola and Chera dynasties. It became a major center for spice trade during the medieval period. The Portuguese and later Dutch and British colonized parts of Kerala. The state was unified after independence. Kerala\'s contribution to Indian cinema, literature, and arts is significant. Traditional art forms like Kathakali and Koodiyatta are world-famous.', speciality: 'Backwaters, Ayurveda, Spice Plantations', image: '/images/states/kerla.jpeg', cardImage: '/images/states/kerla.jpeg', color: '#228B22', region: 'South' },
    { name: 'Tamil Nadu', capital: 'Chennai', famousFood: 'Dosa & Sambar', biggestFestival: 'Pongal', history: 'The cradle of Dravidian civilization, Tamil Nadu is home to ancient temples with intricate Chola architecture. The state has a rich literary tradition dating back thousands of years with the Sangam literature. Classical arts like Bharatanatyam dance and Carnatic music originated here. The Tamil language is one of the oldest surviving languages in the world.', detailedHistory: 'Tamil Nadu was ruled by the Chola, Chera, and Pandya dynasties who were patrons of arts and culture. The state was under colonial rule and later became a center of social reform movements. Modern Tamil Nadu is known for its film industry, textile production, and automobile manufacturing. The Brihadeeswara Temple is a UNESCO World Heritage site.', speciality: 'Temples, Classical Arts, Silk Weaving', image: '/images/states/tamilnadu.jpeg', cardImage: '/images/states/tamilnadu.jpeg', color: '#DC143C', region: 'South' },
    { name: 'Karnataka', capital: 'Bengaluru', famousFood: 'Bisi Bele Bath', biggestFestival: 'Mysore Dasara', history: 'Karnataka is a land of contrasts with IT hubs in the cities and coffee plantations in the Western Ghats. The state was the seat of the mighty Vijayanagara Empire, which built architectural marvels like Hampi. Bengaluru has transformed into India\'s Silicon Valley. The state is rich in biodiversity and mineral resources.', detailedHistory: 'Karnataka was ruled by various dynasties including the Chalukyas and Hoysalas. The Vijayanagara Empire made it a cultural and political center. Later, the state came under British control. Post-independence, Karnataka has been a leader in technology, education, and commerce. The state has contributed significantly to Indian literature, cinema, and music.', speciality: 'IT Hub, Coffee, Temples, Silk', image: '/images/states/karnataka.jpeg', cardImage: '/images/states/karnataka.jpeg', color: '#4169E1', region: 'South' },
    { name: 'Andhra Pradesh', capital: 'Amaravati', famousFood: 'Hyderabadi Biryani', biggestFestival: 'Ugadi', history: 'Andhra Pradesh has a glorious history dating back to the Maurya and Satavahana empires. The state was an important center of Buddhism with Nalanda and Amaravati being major pilgrimage sites. Hyderabad, the former capital, was ruled by the Nizams and was known for its splendor and culture. The state is famous for its pearls and diamonds.', detailedHistory: 'Ancient Andhra was home to thriving Buddhist centers and seat of powerful dynasties. The region came under Mughal, then British rule. Hyderabad was a princely state until 1948. The state is known for its contributions to Telugu cinema, classical music, and dance. Traditional crafts like Bidriware and Ikat weaving are celebrated worldwide.', speciality: 'Pearls, Biryani, Classical Arts', image: '/images/states/andhrapradesh.jpeg', cardImage: '/images/states/andhrapradesh.jpeg', color: '#FF6347', region: 'South' },
    { name: 'Telangana', capital: 'Hyderabad', famousFood: 'Hyderabadi Biryani', biggestFestival: 'Bonalu', history: 'Telangana, India\'s youngest state, separated from Andhra Pradesh in 2014. Hyderabad is the heart of Telangana, known as the City of Pearls and now a major IT and pharma hub. The state has a unique blend of Nizami culture with modern development. Charminar and Golconda Fort are iconic monuments reflecting the state\'s rich heritage.', detailedHistory: 'Telangana was part of the Hyderabad State ruled by the Nizams, who were patrons of arts and culture. The region has a strategic location and rich mineral resources. Post-independence as a separate state, Telangana has rapidly developed economically while preserving its cultural heritage. The state is known for its biryani, pearls, and growing tech industry.', speciality: 'IT Industry, Biryani, Pearls', image: '/images/states/telengana.jpeg', cardImage: '/images/states/telengana.jpeg', color: '#FF69B4', region: 'South' },
    
    // West India
    { name: 'Maharashtra', capital: 'Mumbai', famousFood: 'Vada Pav', biggestFestival: 'Ganesh Chaturthi', history: 'Maharashtra is home to the Maratha Empire, which was a major political force in medieval India. Mumbai, the financial capital, is a global hub for finance and entertainment. The state has a rich history of social reform movements and freedom struggle. Bollywood has shaped modern Indian cinema. The coastal state has a unique blend of history and modernity.', detailedHistory: 'Maharashtra was the heart of the Maratha Empire under leaders like Chhatrapati Shivaji. The region came under British rule and was a center of resistance. Post-independence, Maharashtra emerged as India\'s economic powerhouse. The state has contributed to Indian cinema, literature, and social movements. Traditional art forms like Tamasha and Gondhal are integral to Maharashtrian culture.', speciality: 'Bollywood, Finance, Maratha Heritage', image: '/images/states/maharshtras.jpeg', cardImage: '/images/states/maharshtras.jpeg', color: '#FF9933', region: 'West' },
    { name: 'Gujarat', capital: 'Gandhinagar', famousFood: 'Dhokla & Thepla', biggestFestival: 'Navratri', history: 'The birthplace of Mahatma Gandhi, Gujarat has played a pivotal role in India\'s independence movement. The state was a major center of trade and commerce along the Silk Route. Ahmedabad is known for its textile industry. The state has a strong entrepreneurial spirit and is a leader in manufacturing. The Sabarmati Ashram and various temples reflect its spiritual heritage.', detailedHistory: 'Gujarat was ruled by various dynasties including the Solanki and later the Mughals and British. The region became a center of business and trade. Mahatma Gandhi\'s non-violent resistance movement originated here. Post-independence, Gujarat became a model for industrial and agricultural development. The state is known for its diamond cutting, textile weaving, and handicrafts.', speciality: 'Mahatma Gandhi, Trade, Diamonds', image: '/images/states/gujarat.jpeg', cardImage: '/images/states/gujarat.jpeg', color: '#FF4500', region: 'West' },
    { name: 'Goa', capital: 'Panaji', famousFood: 'Fish Curry Rice', biggestFestival: 'Carnival', history: 'Goa is known for its beaches, colonial architecture, and relaxed lifestyle. The state was under Portuguese rule for over 450 years, which influenced its culture, cuisine, and architecture. The liberation of Goa in 1961 was a significant event. The state has a unique blend of Indian and Portuguese cultures. Church Square in Panaji and Fort Aguada are architectural landmarks.', detailedHistory: 'Goa was colonized by the Portuguese and became a major trading post. The state has a Christian population due to Portuguese influence. The liberation movement in Goa was unique with the Indian Navy intervening. Post-liberation, Goa has developed as a major tourist destination. The state has contributed significantly to Indian music, arts, and literature with a distinct cultural identity.', speciality: 'Beaches, Colonial Architecture, Seafood', image: '/images/states/goa.jpeg', cardImage: '/images/states/goa.jpeg', color: '#00CED1', region: 'West' },
    
    // East India
    { name: 'West Bengal', capital: 'Kolkata', famousFood: 'Fish Curry & Rice', biggestFestival: 'Durga Puja', history: 'West Bengal is the cultural capital of India with contributions to literature, cinema, and arts. Kolkata was the capital of British India and a center of renaissance movements. The state produced Nobel laureate Rabindranath Tagore and filmmaker Satyajit Ray. The Darjeeling tea gardens and the Sundarbans mangrove forests are natural treasures. The state has a rich tradition of intellectual and artistic pursuits.', detailedHistory: 'West Bengal was the seat of powerful kingdoms like the Gupta Empire. It came under British rule and became a center of political and social reform. The Indian National Congress was founded in Kolkata. The Bengal Renaissance produced great intellectuals and revolutionaries. Post-independence, West Bengal became a cultural and political hub. The state is known for its cinema, literature, and traditional Durga Puja celebrations.', speciality: 'Literature, Cinema, Durga Puja', image: '/images/states/west bangal.jpeg', cardImage: '/images/states/west bangal.jpeg', color: '#800080', region: 'East' },
    { name: 'Odisha', capital: 'Bhubaneswar', famousFood: 'Pakhala Bhata', biggestFestival: 'Jagannath Rath Yatra', history: 'Odisha is home to the famous Jagannath Temple in Puri, one of the four sacred dhams. The state was the seat of the Kalinga Empire, known for its trade and artistic traditions. The region witnessed the historic Kalinga War. Odisha is famous for its tribal culture and handicrafts like Odishi paintings and stone carving. The Jagannath Rath Yatra is the world\'s largest chariot festival.', detailedHistory: 'Ancient Odisha (Kalinga) was a major power and cultural center. The region had flourishing trade routes. Odisha has a rich tradition of architecture, art, and dance. The Odishi classical dance form is recognized worldwide. The state is known for its tribal arts, handicrafts, and mineral resources. Odisha has contributed significantly to Indian sculpture and painting traditions.', speciality: 'Jagannath Temple, Odishi Dance, Handicrafts', image: '/images/states/odisha.jpeg', cardImage: '/images/states/odisha.jpeg', color: '#FF1493', region: 'East' },
    { name: 'Jharkhand', capital: 'Ranchi', famousFood: 'Litti Chokha', biggestFestival: 'Sarhul', history: 'Jharkhand is rich in mineral resources and tribal heritage. The state is known for its forests and wildlife. Jamshedpur was the first planned industrial city in India, built by Tata Iron and Steel Company. The state has a vibrant tribal culture with unique festivals and traditional art forms. Waterfalls and natural beauty make it a scenic destination.', detailedHistory: 'Jharkhand was part of various kingdoms historically. The region came under British rule and was developed as an industrial center. Post-independence, it remained part of Bihar until becoming a separate state in 2000. The state is home to indigenous tribal communities with unique cultural practices. Jharkhand contributes significantly to India\'s mineral wealth and power generation.', speciality: 'Tribal Culture, Minerals, Waterfalls', image: '/images/states/jharkhand.jpeg', cardImage: '/images/states/jharkhand.jpeg', color: '#8FBC8F', region: 'East' },
    { name: 'Bihar', capital: 'Patna', famousFood: 'Litti Chokha', biggestFestival: 'Chhath Puja', history: 'Bihar is one of India\'s oldest inhabited regions and was the seat of the Mauryan Empire. Nalanda University, established in the 5th century, was a renowned center of learning. The state is sacred to Buddhists with Bodh Gaya, the site of Buddha\'s enlightenment. The Ganga River flows through Bihar, making it spiritually significant. Ancient Buddhist stupas and archaeological sites are important heritage sites.', detailedHistory: 'Bihar was the birthplace of Buddhism and Jainism. The Mauryan Empire made Pataliputra (Patna) a great capital. The region was a center of learning and culture. Bihar came under British rule and later saw significant freedom struggle activities. Post-independence, Bihar has been an important spiritual and educational center. The state is working to preserve its Buddhist heritage and archaeological treasures.', speciality: 'Bodh Gaya, Nalanda, Buddhist Heritage', image: '/images/states/bihar.jpeg', cardImage: '/images/states/bihar.jpeg', color: '#DEB887', region: 'East' },
    
    // Northeast India
    { name: 'Assam', capital: 'Dispur', famousFood: 'Assam Laksa', biggestFestival: 'Bihu', history: 'Assam is the gateway to Northeast India, known for its tea gardens and wildlife. The Brahmaputra Valley is home to the Indian rhinoceros. Assam has a rich history under the Ahom dynasty and later British rule. The state is a melting pot of cultures with various indigenous tribes. The Kaziranga and Manas Wildlife Sanctuaries are UNESCO World Heritage sites.', detailedHistory: 'Assam was ruled by the Ahom dynasty for over 600 years, who developed sophisticated administrative systems. The region became a major tea-producing area during British rule. Post-independence, Assam became important for its natural resources and wildlife. The state has diverse tribal communities each with unique cultural practices. Assam has contributed significantly to Indian agriculture and wildlife conservation.', speciality: 'Tea, Rhinos, Brahmaputra Valley', image: '/images/states/assam.jpeg', cardImage: '/images/states/assam.jpeg', color: '#32CD32', region: 'Northeast' },
    { name: 'Meghalaya', capital: 'Shillong', famousFood: 'Jadoh', biggestFestival: 'Wangala', history: 'Meghalaya, the abode of clouds, is one of the wettest places on Earth. The state is famous for its living root bridges, a unique form of bio-engineering by the Khasi tribe. Shillong is known as the Scotland of the East. The state has a matrilineal society where property is inherited through the female line. Cherrapunji in Meghalaya holds the record for highest rainfall.', detailedHistory: 'Meghalaya was part of Assam until 1972 when it became a separate state. The region has indigenous tribal communities with unique governance systems. The living root bridges are a testament to the ingenuity and environmental harmony of the Khasi people. The state is a center of adventure tourism and natural beauty. Meghalaya has preserved traditional practices and sustainable living traditions.', speciality: 'Living Root Bridges, Rainfall, Tribal Culture', image: '/images/states/meghalaya.jpeg', cardImage: '/images/states/meghalaya.jpeg', color: '#20B2AA', region: 'Northeast' },
    { name: 'Manipur', capital: 'Imphal', famousFood: 'Eromba', biggestFestival: 'Lai Haraoba', history: 'Manipur, the jewel of India, is famous for its classical dance form, Manipuri dance, which is recognized worldwide. The state has a rich literary and artistic tradition. Loktak Lake with its floating islands is a unique ecosystem. The state was an independent kingdom until it merged with India. Manipur is known for its fine arts, music, and handicrafts.', detailedHistory: 'Manipur was an independent kingdom with its own governance and culture for centuries. The kingdom came under British rule and later merged with India. The state is the origin of classical Manipuri dance and music. Manipur has a vibrant arts scene with contributions to Indian cinema and literature. The state is known for its traditional martial arts and sports achievements.', speciality: 'Manipuri Dance, Loktak Lake, Arts', image: '/images/states/manipur.jpeg', cardImage: '/images/states/manipur.jpeg', color: '#FF7F50', region: 'Northeast' },
    { name: 'Tripura', capital: 'Agartala', famousFood: 'Mui Borok', biggestFestival: 'Kharchi Puja', history: 'Tripura is known for its bamboo handicrafts and tribal culture. The state was an ancient kingdom with a rich heritage. Ujjayanta Palace in Agartala is an architectural marvel. The state has a unique blend of Bengali and tribal cultures. Tripura is famous for its rubber plantations and silk weaving.', detailedHistory: 'Tripura was ruled by Indian kings who were patrons of arts and culture. The state came under British protection and later merged with India. Tripura has diverse tribal populations each with unique traditions. The state is known for its rubber and silk production. Post-independence, Tripura has developed as an important cultural and industrial center in the Northeast.', speciality: 'Bamboo Crafts, Rubber, Silk Weaving', image: '/images/states/tripura.jpeg', cardImage: '/images/states/tripura.jpeg', color: '#DA70D6', region: 'Northeast' },
    
    // Central India
    { name: 'Madhya Pradesh', capital: 'Bhopal', famousFood: 'Poha Jalebi', biggestFestival: 'Khajuraho Dance Festival', history: 'Madhya Pradesh, the Heart of India, is known for its ancient temples and tribal culture. The Khajuraho temples with their intricate sculptures are a UNESCO World Heritage site. The state was the center of the Malwa region, known for art and culture. Bhopal is surrounded by lakes and is a city of culture and spirituality. The state has rich mineral resources and forest cover.', detailedHistory: 'Madhya Pradesh was ruled by various dynasties including the Chandelas who built the Khajuraho temples. The region had important kingdoms and was a center of trade. The state came under British rule. Post-independence, Madhya Pradesh became a leader in forest conservation and tribal rights. The state is known for its diamond mines and handicrafts.', speciality: 'Khajuraho Temples, Diamond Mines, Tribal Art', image: '/images/states/mp.jpeg', cardImage: '/images/states/mp.jpeg', color: '#DAA520', region: 'Central' },
    { name: 'Chhattisgarh', capital: 'Raipur', famousFood: 'Chila', biggestFestival: 'Bastar Dussehra', history: 'Chhattisgarh is known for its tribal heritage and mineral wealth. The state was part of the ancient Dandaka forest region and is home to various tribal communities. The state is rich in coal, iron, and other minerals. Chhattisgarh is known for its tribal art and handicrafts. The state is working to preserve tribal culture while developing economically.', detailedHistory: 'Chhattisgarh was part of various kingdoms and later came under British rule as part of the Central Provinces. The state was formed in 2000 as a separate state. The region has ancient monuments and archaeological sites. Chhattisgarh is known for its tribal dances, art forms, and handicrafts. The state is a major contributor to India\'s mineral wealth and energy production.', speciality: 'Tribal Art, Minerals, Forests', image: '/images/states/chattisgarh.jpeg', cardImage: '/images/states/chattisgarh.jpeg', color: '#CD853F', region: 'Central' }
  ]

  return (
    <main className="min-h-screen pt-16">
      {/* Hero Section */}
      <section className="bg-gradient-to-br from-saffron/20 via-peacock/20 to-maroon/20 py-20">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <motion.h1
            initial={{ opacity: 0, y: 50 }}
            animate={{ opacity: 1, y: 0 }}
            className="font-playfair text-5xl md:text-6xl font-bold text-maroon mb-6"
          >
            States of India 🗺️
          </motion.h1>
          <motion.p
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.3 }}
            className="text-xl text-gray-700 max-w-3xl mx-auto"
          >
            Explore the unique culture, cuisine, festivals, and history of every Indian state
          </motion.p>
        </div>
      </section>

      {/* Interactive Map */}
      <section className="py-20">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <InteractiveMap states={states} />
        </div>
      </section>

      {/* States Grid */}
      <section className="py-20 bg-gray-50">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <motion.h2
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="font-playfair text-4xl font-bold text-center text-maroon mb-16"
          >
            Discover Every State
          </motion.h2>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            {states.map((state, index) => (
              <StateCard 
                key={state.name} 
                state={state} 
                index={index}
                onOpenModal={(state) => {
                  setSelectedState(state)
                  setIsModalOpen(true)
                }}
              />
            ))}
          </div>
        </div>
      </section>

      {/* State Modal */}
      <StateModal 
        isOpen={isModalOpen}
        state={selectedState}
        onClose={() => {
          setIsModalOpen(false)
          setSelectedState(null)
        }}
      />
    </main>
  )
}